# Generated by Django 4.2 on 2023-05-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_product_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
