# Generated by Django 4.2 on 2023-05-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_remove_product_profile_pic_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='index.png', null=True, upload_to=''),
        ),
    ]
